### ISSUE TITLE
Impossibile scaricare lezioni del 29/09/2021

### ISSUE THREAD

**Issue by GiacomoC00** [beryxz/unifi-webex-dl#4]
Risulta impossibile scaricare tutte le lezioni caricate su Webex in data 29/09/2021 (indipendentemente dal corso).

**Comment by MattiaManneschi** [comment]
succede anche a me la stessa identica cosa.

**Comment by beryxz** [comment]
@GiacomoC00 @MattiaManneschi Ora dovrebbe funzionare. Vi è possibile riprovare usando le modifiche sul branch `dev`?

**Comment by Voltagen99** [comment]
Dopo l'update riesco a scaricare tutte le lezioni tranne una di Analisi 2.
Quando la processa stampa questo errore:
Skipped because of: Request failed with status code 404

**Comment by beryxz** [comment]
@Voltagen99 Possibile che la lezione si una di prova che è stata disattivata dal docente?
Basta provare ad aprirla su webex per verificare. Altrimenti avrei bisogno dell'id del corso su Moodle, così da provare.

**Comment by GiacomoC00** [comment]
ora sembra funzionare ma le lezioni di oggi del corso di geometria e algebra lineare laurea in ingegneria informatica le scarica molto lentamente
![Cattura](https://user-images.githubusercontent.com/76397745/135336287-37a5a309-1359-4229-9841-8df853ca6e6f.PNG)

**Comment by beryxz** [comment]
@GiacomoC00 queste lezioni le ha per caso scaricate come stream? Ovvero, è apparso "Trying downloading stream" prima di iniziare a scaricarle?
Purtroppo sulla velocità di download c'è poco che possa fare, dipende dallo stato di webex.
Segno nei TODO la parallelizzazione del download dei segmenti dello stream.

**Comment by GiacomoC00** [comment]
guarda ho allegato la foto al messaggio precedente

**Comment by GiacomoC00** [comment]
le lezioni lei in teoria non le farebbe scaricare da webex perché non le ha rese disponibili al download ma fino a lunedì il tuo programmino le scaricava lo stesso. Al momento sembra che le scarichi lo stesso ma molto molto lentamente

**Comment by beryxz** [comment]
Eh si, il motivo è quello. Quando il download della registrazione è stato disattivato dal docente, viene sfruttato il fatto che comunque uno possa guardarla. Il fatto è che questa seconda modalità suddivide la registrazione in segmenti che per il momento vengono scaricati sequenzialmente.

**Comment by GiacomoC00** [comment]
ok capito

**Comment by GiacomoC00** [comment]
però adesso non riesce a terminare il download di queste lezioni in particolare 
è la seconda volta che si chiude da solo

**Comment by GiacomoC00** [comment]
il motivo quale potrebbe essere?

**Comment by beryxz** [comment]
Da qualche errore particolare o semplicemente si chiude?
Sto provando a replicare il problema con lo stesso corso

**Comment by GiacomoC00** [comment]
non ho visto nessun errore

**Comment by GiacomoC00** [comment]
ho riprovato e si chiude senza nessun errore

**Comment by GiacomoC00** [comment]
comunque sei hai bisogno di altri feedback anche domani sarò lieto di aiutare

**Comment by Voltagen99** [comment]
No, la lezione è regolare ma non scaricabile. Prima del crash ogni lezione
di Analisi 2 riportava un warn giallo ma scaricava tutto, anche se in piú
tempo.

Il Mer 29 Set 2021, 21:10 Lorenzo ***@***.***> ha scritto:

**Comment by beryxz** [comment]
@Voltagen99 Allora dovrei provare a replicare il problema, avrei però bisogno:
- Id del corso su Moodle
- Nome della registrazione che ti da problemi

**Comment by beryxz** [comment]
@GiacomoC00 Non riesco a replicare questo problema. Che fosse un problema temporaneo di webex?
Se il problema ti persiste, prova ad attivare i log di debug con `LOG_LEVEL=debug npm start` e fammi sapere.

**Comment by GiacomoC00** [comment]
@beryxz Avevi ragione era solo un problema di webex in merito a quelle lezioni di geometria. Comunque ti posso confermare che la versione dev attuale non presenta più tutti gli altri problemi, i fix che hai applicato sembrano funzionare bene.
