### ISSUE TITLE
[BUG] text.replaceAll is not a function

### ISSUE THREAD

**Issue by naldoxable** [beryxz/unifi-webex-dl#9]
Appena aggiornato alla versione 8.0.0 riscontro questo errore:

<img width="729" alt="Schermata 2022-03-03 alle 11 44 14" src="https://user-images.githubusercontent.com/39309440/156549204-8cbe9443-cd41-47ca-b6d1-cd4e89606ebd.png">

**Comment by naldoxable** [comment]
Adesso, dopo aver rilanciato più volte l'app, a volte propone un errore diverso da quello sopra:

<img width="692" alt="Schermata 2022-03-03 alle 11 54 31" src="https://user-images.githubusercontent.com/39309440/156551109-98e5a5d3-2535-4e6b-b1eb-4283d4a4a814.png">

Il programma ha sempre funzionato in passato

**Comment by beryxz** [comment]
Ciao, grazie per aver fatto presente il problema.
In effetti con la versione 8.0.0 il programma non è più compatibile con Node 14.

Ho rilasciato la nuova versione 8.0.1 che dovrebbe risolvere questo problema. Riesci a provarla?

Il problema dell'autenticazione con Moodle non sono riuscito a replicarlo, possible fosse un problema momentaneo della piattaforma. Se il problema persiste, farei una nuova issue apposita dove indagare il problema più a fondo.

**Comment by naldoxable** [comment]
Problema risolto! Grazie
